// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DiscoveryBDDTest.FeatureFiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("deliveryOptions")]
    public partial class DeliveryOptionsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "deliveryOptions.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "deliveryOptions", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("deliveryOptions")]
        [NUnit.Framework.TestCaseAttribute("C2849839", "StaffIn", "AcademicSubscription", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available to view in one of our reading rooms", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[3]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record may also be available on other websites.", "Visit Adam Matthew", "The National Archives", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "Request a quote for a copy to be sent to you via email or post (£)", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C2849839", "StaffIn", "AcademicSubscription", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available to view in one of our reading rooms", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[3]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record may also be available on other websites.", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "Request a quote for a copy to be sent to you via email or post (£)", "Order a copy", "Page Check Request", null)]
        [NUnit.Framework.TestCaseAttribute("C4216021", "StaffIn", "AccessUnderReview", "(//div[@class=\'order-option-wrapper\'])", "This record is closed whilst access is under review", "Submit FOI request", "Contact us", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C5040641", "StaffIn", "AccessUnderReview", "(//div[@class=\'order-option-wrapper\'])", "This record is closed whilst access is under review", "Submit FOI request", "Contact us", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C1960950", "StaffIn", "AccessUnderReview", "(//div[@class=\'order-option-wrapper\'])", "This record is closed whilst access is under review", "Submit FOI request", "Contact us", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C14016274", "StaffIn", "AV_Media", "(//div[@class=\'order-option-wrapper\'])", "View this on the Discovery Video Player", "Discovery Video Player", "Video:", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C14016274", "StaffIn", "AV_Media", "(//div[@class=\'order-option-wrapper\'])", "View this on the Discovery Video Player", "Visit Discovery Video Player", "Video:", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C14016322", "StaffIn", "AV_Media", "(//div[@class=\'order-option-wrapper\'])", "View this on the Discovery Video Player", "Discovery Video Player", "Video:", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C14016322", "StaffIn", "AV_Media", "(//div[@class=\'order-option-wrapper\'])", "View this on the Discovery Video Player", "Visit Discovery Video Player", "Video:", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C10853769", "StaffIn", "ClosedFOIReview", "(//div[@class=\'order-option-wrapper\'])", "This record is closed", "Submit FOI request", "Contact us", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C4633754", "StaffIn", "ClosedFOIReview", "(//div[@class=\'order-option-wrapper\'])", "This record is closed", "Submit FOI request", "Contact us", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C11362729", "StaffIn", "ClosedRetainedDeptKnown", "(//div[@class=\'order-option-wrapper\'])", "This record is closed and retained by Department for Business, Energy and Industr" +
            "ial Strategy", "Visit the department website", "The National Archives", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C3836961", "StaffIn", "ClosedRetainedDeptUnKnown", "(//div[@class=\'order-option-wrapper\'])", "This record is retained by a government department", "Contact us", "The National Archives", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C543521", "StaffIn", "CollectionCare", "(//div[@class=\'order-option-wrapper\'])[1]", "This record requires supervised handling in Collection Care", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "Please contact a member of staff to arrange a viewing.", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "Please contact The National Archives to arrange viewing.", "contact", "Contact us", null)]
        [NUnit.Framework.TestCaseAttribute("C543521", "StaffIn", "CollectionCare", "(//div[@class=\'order-option-wrapper\'])[1]", "This record requires supervised handling in Collection Care", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "Please contact a member of staff to arrange a viewing.", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "Please contact The National Archives to arrange viewing.", "contact us", "Contact us", null)]
        [NUnit.Framework.TestCaseAttribute("C6208104", "StaffIn", "DigitizedAvailableButNotDownloadableAtItemLevel", "//div[@class=\'order-option-wrapper\']", "This record has been digitised as part of the larger record", "Go to record", "The National Archives", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C1905025", "StaffIn", "DigitizedAvailableButNotDownloadableAtPieceLevel", "//div[@class=\'order-option-wrapper\']", "This record has been digitised as part of multiple records", "Go to browse", "Browse records of other archives", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C7351413", "StaffIn", "DigitizedDiscovery", "//div[@class=\'order-option-wrapper\']", "Download this record", "Download now", "The National Archives", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C7351413", "StaffIn", "DigitizedDiscovery", "//div[@class=\'order-option-wrapper\']", "Download this record", "", "", "//div[@id=\'staffViewOfOtherUserDOsWrapper\']/a", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[2]", "Ordering and viewing options", "Add to basket", "The National Archives", null)]
        [NUnit.Framework.TestCaseAttribute("C198022", "StaffIn", "DigitizedDiscovery", "//div[@class=\'order-option-wrapper\']", "Download this record", "Download now", "The National Archives", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C198022", "StaffIn", "DigitizedDiscovery", "//div[@class=\'order-option-wrapper\']", "Download this record", "", "", "//div[@id=\'staffViewOfOtherUserDOsWrapper\']/a", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[2]", "Ordering and viewing options", "Add to basket", "The National Archives", null)]
        [NUnit.Framework.TestCaseAttribute("C2490774", "StaffIn", "DigitizedLia", "(//div[@class=\'order-option-wrapper\'])[1]", "This is available to download from The Genealogist", "Visit The Genealogist", "The National Archives", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[3]", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C2490774", "StaffIn", "DigitizedLia", "(//div[@class=\'order-option-wrapper\'])[1]", "This is available to download from The Genealogist", "The Genealogist", "The National Archives", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[3]", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C2490774", "StaffIn", "DigitizedLia", "(//div[@class=\'order-option-wrapper\'])[1]", "This is available to download from The Genealogist", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[3]", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[2]", "This is available to download from The Genealogist", "Visit The Genealogist[2]", "The National Archives", null)]
        [NUnit.Framework.TestCaseAttribute("C2490774", "StaffIn", "DigitizedLia", "(//div[@class=\'order-option-wrapper\'])[1]", "This is available to download from The Genealogist", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[3]", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[2]", "This is available to download from The Genealogist", "The Genealogist[2]", "The National Archives", null)]
        [NUnit.Framework.TestCaseAttribute("C1847980", "StaffIn", "DigitizedOther", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available from:", "Findmypast", "The National Archives", "//div[@id=\'staffViewOfOtherUserDOsWrapper\']/a", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C1847980", "StaffIn", "DigitizedOther", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available from:", "", "", "//div[@id=\'staffViewOfOtherUserDOsWrapper\']/a", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[2]", "This record is available from:", "Findmypast[2]", "The National Archives", null)]
        [NUnit.Framework.TestCaseAttribute("C393557", "StaffIn", "DisplayAtMuseum", "(//div[@class=\'order-option-wrapper\'])[1]", "Contact us to find out if you can view a copy at The National Archives.", "Contact us", "The National Archives", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C393557", "StaffIn", "DisplayAtMuseum", "(//div[@class=\'order-option-wrapper\'])[1]", "Contact us to find out if you can view a copy at The National Archives.", "Contact us[2]", "The National Archives", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C393557", "StaffIn", "DisplayAtMuseum", "(//div[@class=\'order-option-wrapper\'])[1]", "Contact us to find out if you can view a copy at The National Archives.", "the Keepers’ Gallery", "The National Archives", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C393557", "StaffIn", "DisplayAtMuseum", "(//div[@class=\'order-option-wrapper\'])[1]", "Contact us to find out if you can view a copy at The National Archives.", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "Ask a member of staff if you can view a copy of this record", "the Keepers’ Gallery[2]", "The National Archives", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C16665", "StaffIn", "GovtWebArchive", "(//div[@class=\'order-option-wrapper\'])", "This record is held by the UK Government Web Archive.", "", "", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C4771085", "StaffIn", "InUse", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is currently in use", "", "", "//div[@id=\'staffViewOfOtherUserDOsWrapper\']/a", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[2]", "This record has not been digitised and cannot be downloaded.", "order records in advance", "The National Archives", null)]
        [NUnit.Framework.TestCaseAttribute("C4771085", "StaffIn", "InUse", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is currently in use", "", "", "//div[@id=\'staffViewOfOtherUserDOsWrapper\']/a", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[2]", "This record has not been digitised and cannot be downloaded.", "visit Kew", "Visit us", null)]
        [NUnit.Framework.TestCaseAttribute("C4771085", "StaffIn", "InUse", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is currently in use", "", "", "//div[@id=\'staffViewOfOtherUserDOsWrapper\']/a", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[2]", "This record has not been digitised and cannot be downloaded.", "reader\'s ticket", "Do I need a reader\'s ticket?", null)]
        [NUnit.Framework.TestCaseAttribute("C4771085", "StaffIn", "InUse", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is currently in use", "", "", "//div[@id=\'staffViewOfOtherUserDOsWrapper\']/a", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[2]", "This record has not been digitised and cannot be downloaded.", "Order in advance", "Order documents in advance", null)]
        [NUnit.Framework.TestCaseAttribute("C4771085", "StaffIn", "InUse", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is currently in use", "", "", "//div[@id=\'staffViewOfOtherUserDOsWrapper\']/a", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[2]", "This record has not been digitised and cannot be downloaded.", "Request a copy", "Page Check Request", null)]
        [NUnit.Framework.TestCaseAttribute("C1699211", "StaffIn", "LocalArchive", "(//div[@class=\'order-option-wrapper\'])", "This record is held by National Maritime Museum: The Caird Library and Archive", "See contact details", "The National Archives", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C2547266", "StaffIn", "MissingLost", "(//div[@class=\'order-option-wrapper\'])", "This record is missing and is unavailable", "", "", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C4364677", "StaffIn", "MouldTreatment", "(//div[@class=\'order-option-wrapper\'])[1]", "This record requires treatment for mould", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record requires treatment for mould", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "This record requires treatment for mould", "contact", "Contact us", null)]
        [NUnit.Framework.TestCaseAttribute("C4364677", "StaffIn", "MouldTreatment", "(//div[@class=\'order-option-wrapper\'])[1]", "This record requires treatment for mould", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record requires treatment for mould", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "This record requires treatment for mould", "Contact us", "Contact us", null)]
        [NUnit.Framework.TestCaseAttribute("C2698319", "StaffIn", "Offsite", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is held off site", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[5]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record is held off site", "Advanced order", "Order documents in advance", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C2698319", "StaffIn", "Offsite", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is held off site", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[5]", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "This record has not been digitised and cannot be downloaded.", "order records in advance", "The National Archives", null)]
        [NUnit.Framework.TestCaseAttribute("C2698319", "StaffIn", "Offsite", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is held off site", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[5]", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "This record has not been digitised and cannot be downloaded.", "visit Kew", "Visit us", null)]
        [NUnit.Framework.TestCaseAttribute("C2698319", "StaffIn", "Offsite", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is held off site", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[5]", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "This record has not been digitised and cannot be downloaded.", "reader\'s ticket", "Do I need a reader\'s ticket?", null)]
        [NUnit.Framework.TestCaseAttribute("C2698319", "StaffIn", "Offsite", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is held off site", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[5]", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "This record has not been digitised and cannot be downloaded.", "Order in advance", "Order documents in advance", null)]
        [NUnit.Framework.TestCaseAttribute("C2698319", "StaffIn", "Offsite", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is held off site", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[5]", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "This record has not been digitised and cannot be downloaded.", "Order a copy", "Page Check Request", null)]
        [NUnit.Framework.TestCaseAttribute("90ad00a1aa6149efa3991fab6037a5ec", "StaffIn", "PaidSearch", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is closed", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[2]", "This record is closed", "Request a search of closed records", "Request a search of closed records", null)]
        [NUnit.Framework.TestCaseAttribute("C2050263", "StaffIn", "Surrogate", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available to view in one of our reading rooms", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record is available to view in one of our reading rooms", "reader\'s ticket", "The National Archives", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C2050263", "StaffIn", "Surrogate", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available to view in one of our reading rooms", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "This record has not been digitised and cannot be downloaded.", "Order a copy", "Page Check Request", null)]
        [NUnit.Framework.TestCaseAttribute("C9188919", "StaffIn", "Surrogate", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available to view in one of our reading rooms", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record is available to view in one of our reading rooms", "reader\'s ticket", "The National Archives", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C9188919", "StaffIn", "Surrogate", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available to view in one of our reading rooms", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "This record has not been digitised and cannot be downloaded.", "Order a copy", "Page Check Request", null)]
        [NUnit.Framework.TestCaseAttribute("C4560825", "StaffIn", "TooLargeToCopyOriginal", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available to order and view", "Order now", "The National Archives", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[4]", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C6934963", "StaffIn", "TooLargeToCopySurrogate", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available to view in one of our reading rooms", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[1]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record is available to view in one of our reading rooms", "reader\'s ticket", "The National Archives", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C8135237", "StaffIn", "TooLargeToCopySurrogate", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available to view in one of our reading rooms", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[1]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record is available to view in one of our reading rooms", "reader\'s ticket", "The National Archives", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C8135239", "StaffIn", "TooLargeToCopySurrogate", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available to view in one of our reading rooms", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[1]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record is available to view in one of our reading rooms", "reader\'s ticket", "The National Archives", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C6934963", "StaffIn", "TooLargeToCopySurrogate", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available to view in one of our reading rooms", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[1]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record is available to view in one of our reading rooms", "Image Library", "The National Archives", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C6934963", "StaffIn", "TooLargeToCopySurrogate", "(//div[@class=\'order-option-wrapper\'])[1]", "This record is available to view in one of our reading rooms", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[1]", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "Ordering and viewing options", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C11692008", "StaffIn", "UnAvailable", "(//div[@class=\'order-option-wrapper\'])", "This record is not available to order. More information may be available in the c" +
            "atalogue description.", "", "", "", "", "", "", "", "", "", "", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("C513426", "StaffIn", "Unfit", "(//div[@class=\'order-option-wrapper\'])[1]", "This record requires conservation treatment", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record requires conservation treatment", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "This record requires conservation treatment", "contact", "Contact us", null)]
        [NUnit.Framework.TestCaseAttribute("C513426", "StaffIn", "Unfit", "(//div[@class=\'order-option-wrapper\'])[1]", "This record requires conservation treatment", "", "", "(//a[@class=\'discoveryPrimaryCallToActionLink\'])[2]", "OnSitePublic", "(//div[@class=\'order-option-wrapper\'])[2]", "This record requires conservation treatment", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[3]", "This record requires conservation treatment", "Contact us", "Contact us", null)]
        [NUnit.Framework.TestCaseAttribute("90ad00a1aa6149efa3991fab6037a5ec", "StaffIn", "PaidSearch", "(//div[@class=\'order-option-wrapper\'])[1]", "To request a search of closed records you are required to upload documents as pro" +
            "of that the person is no longer living.", "", "", "//div[@id=\'staffViewOfOtherUserDOsWrapper\']/a", "", "", "", "", "", "OffSite", "(//div[@class=\'order-option-wrapper\'])[2]", "This record is closed", "Request a search of closed records", "Request a search of closed records", null)]
        public virtual void DeliveryOptions(
                    string iaId, 
                    string staffinAttributes, 
                    string deliveryOptionsAttributes, 
                    string staffinStringXPath, 
                    string staffinMessage, 
                    string staffinButton, 
                    string staffinCheckPageTitle, 
                    string deliveryOptionstoOtherUsers, 
                    string onSiteAttributes, 
                    string onSiteStringXPath, 
                    string onsiteMessage, 
                    string onsiteButton, 
                    string onsiteCheckPageTitle, 
                    string offSiteAttributes, 
                    string offSiteStringXPath, 
                    string offsiteMessage, 
                    string offsiteButton, 
                    string offsiteCheckPageTitle, 
                    string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("deliveryOptions", null, exampleTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 4
 testRunner.Given(string.Format("I am on delivery options page for \"{0}\"", iaId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
 testRunner.When(string.Format("I click on \"{0}\"", deliveryOptionstoOtherUsers), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 6
 testRunner.Then(string.Format("check for staffin \"{0}\" ,\"{1}\" ,\"{2}\",\"{3}\"", staffinStringXPath, staffinAttributes, deliveryOptionsAttributes, staffinMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 7
 testRunner.And(string.Format("check for onsite \"{0}\", \"{1}\", \"{2}\", \"{3}\"", onSiteStringXPath, onSiteAttributes, deliveryOptionsAttributes, onsiteMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And(string.Format("check for offsite  \"{0}\", \"{1}\", \"{2}\", \"{3}\"", offSiteStringXPath, offSiteAttributes, deliveryOptionsAttributes, offsiteMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And(string.Format("check for the \"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\",\"{5}\"", staffinButton, staffinCheckPageTitle, onsiteButton, onsiteCheckPageTitle, offsiteButton, offsiteCheckPageTitle), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
