// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DiscoveryBDDTest.FeatureFiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("whatToExpectGuide")]
    public partial class WhatToExpectGuideFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "whatToExpectGuide.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "whatToExpectGuide", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("DidYouFindThisGuideHelpful")]
        [NUnit.Framework.TestCaseAttribute("C7352683", "//*[@id=\"what-to-expect-form\"]/div/form/fieldset/button[1]", "We\'d like to hear from you", "Your feedback helps us improve our services. Please share any comments below (opt" +
            "ional)", "This is a Test", "Thank you for your feedback", null)]
        [NUnit.Framework.TestCaseAttribute("C7352683", "//*[@id=\"what-to-expect-form\"]/div/form/fieldset/button[2]", "Please let us know why you are dissatisfied", "Your feedback helps us improve our services. Please share any comments below", "This is a Test", "Thank you for your feedback", null)]
        [NUnit.Framework.TestCaseAttribute("C14017296", "//*[@id=\"what-to-expect-form\"]/div/form/fieldset/button[1]", "We\'d like to hear from you", "Your feedback helps us improve our services. Please share any comments below (opt" +
            "ional)", "This is a Test", "Thank you for your feedback", null)]
        [NUnit.Framework.TestCaseAttribute("C14017296", "//*[@id=\"what-to-expect-form\"]/div/form/fieldset/button[2]", "Please let us know why you are dissatisfied", "Your feedback helps us improve our services. Please share any comments below", "This is a Test", "Thank you for your feedback", null)]
        public virtual void DidYouFindThisGuideHelpful(string iaId, string button, string heading, string commentHeading, string feedback, string acknowledge, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DidYouFindThisGuideHelpful", null, exampleTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 4
 testRunner.Given(string.Format("I am on the details page for \"{0}\" for offSite", iaId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
 testRunner.When(string.Format("click on \"{0}\" for Did you find this guide helpful", button), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 6
 testRunner.And(string.Format("check for the \"{0}\" and \"{1}\"", heading, commentHeading), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.Then(string.Format("enter \"{0}\", \"{1}\"", feedback, acknowledge), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("readMore_researchGuide")]
        [NUnit.Framework.TestCaseAttribute("C14017295", null)]
        [NUnit.Framework.TestCaseAttribute("C14053146", null)]
        [NUnit.Framework.TestCaseAttribute("C14053152", null)]
        public virtual void ReadMore_ResearchGuide(string iaId, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("readMore_researchGuide", null, exampleTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 17
 testRunner.Given(string.Format("I am on the details page for \"{0}\" for offSite", iaId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
 testRunner.When("click on Read more, click on research guide", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.Then("check for the page title", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("readMore_readLess")]
        [NUnit.Framework.TestCaseAttribute("C14053147", null)]
        [NUnit.Framework.TestCaseAttribute("C14017295", null)]
        public virtual void ReadMore_ReadLess(string iaId, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("readMore_readLess", null, exampleTags);
#line 27
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 28
 testRunner.Given(string.Format("I am on the details page for \"{0}\" for offSite", iaId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 29
 testRunner.When("click on Read more", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("click on Read less", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("ViewExampleRecord")]
        [NUnit.Framework.TestCaseAttribute("C14016702", null)]
        [NUnit.Framework.TestCaseAttribute("C14053146", null)]
        public virtual void ViewExampleRecord(string iaId, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ViewExampleRecord", null, exampleTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 38
testRunner.Given(string.Format("I am on the details page for \"{0}\" for offSite", iaId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 39
testRunner.When("click on View a page feom an example war diary", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
testRunner.Then("check for the title example record only", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
